backend:
  name: git-gateway
  commit_messages:
    create: "add {{collection}} “{{slug}}”"
    update: "update {{collection}} “{{slug}}”"
    delete: "delete {{collection}} “{{slug}}”"
    uploadMedia: "upload “{{path}}”"
    deleteMedia: "delete “{{path}}”"

media_folder: static/img
public_folder: img
collections:
  - name: blog
    label: Blog
    folder: "content/blog"
    create: true
    editor:
      preview: false
    fields:
      - {
          label: "Título",
          name: "title",
          widget: "string",
          pattern: [".{24,}", "Must have at least 24 characters"],
        }
      - { label: "Data de publicação", name: "date", widget: "datetime" }
      - { label: "Imagem", name: "featuredimage", widget: image }
      - { label: "Descrição", name: "description", widget: "string" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }

  - name: receitas
    label: Receitas
    folder: "content/recipes"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Imagem", name: "featuredimage", widget: image }
      - {
          label: "Categoria",
          name: "category",
          widget: "select",
          options:
            [
              "Bolos e tortas",
              "Carnes",
              "Peixes e frutos do mar",
              "Saladas e molhos",
              "Sopas",
              "Massas",
              "Bebidas",
              "Sobremesas",
              "Lanches",
            ],
        }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
