backend:
  name: git-gateway
media_folder: static/img
public_folder: img
collections:
  - name: blog
    label: Blog
    folder: "content/blog"
    create: true
    fields:
      #   - { name: path, label: Path }
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data de publicação", name: "date", widget: "datetime" }
      - { label: "Imagem", name: "featuredimage", widget: image }
      - { label: "Descrição", name: "description", widget: "string" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
      # - { label: "Tags", name: "tags", widget: "list" }
  - name: receitas
    label: Receitas
    folder: "content/recipes"
    create: true
    fields:
      #   - { name: path, label: Path }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Data de publicação", name: "date", widget: "datetime" }
      - { label: "Imagem", name: "featuredimage", widget: image }
      - { label: "Descrição", name: "description", widget: "string" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
